# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, choices=[('判断', '判断'), ('单选', '单选'), ('多选', '多选'), ('填空', '填空'), ('简答', '简答'), ('论述', '论述')], max_length=10, null=True, verbose_name='试题类型')),
                ('reference_answer', models.TextField(blank=True, null=True, verbose_name='参考答案')),
                ('question_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='试题名称')),
                ('question_text', models.TextField(blank=True, null=True, verbose_name='试题问题')),
                ('choice_text', models.TextField(blank=True, null=True, verbose_name='选择题选项配置')),
                ('question_image_data', models.BinaryField(blank=True, null=True, verbose_name='题目图片')),
                ('difficulty_level', models.CharField(blank=True, choices=[('easy', '简单'), ('middle', '中等'), ('hard', '困难')], max_length=15, null=True, verbose_name='难易程度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='出题描述')),
                ('subject', models.CharField(blank=True, max_length=150, null=True, verbose_name='学科')),
                ('question_database', models.CharField(blank=True, max_length=150, null=True, verbose_name='题库名称')),
                ('author', models.CharField(blank=True, max_length=50, null=True, verbose_name='出题人')),
            ],
            options={
                'verbose_name': '考试试题',
                'db_table': 'exam_question',
            },
        ),
    ]
