# encoding=utf-8
# Generated by Django 3.2.23 on 2024-02-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammanage',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='考试管理创建时间'),
        ),
        migrations.AlterField(
            model_name='exammanage',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='考试时长'),
        ),
        migrations.AlterField(
            model_name='exammanage',
            name='exam_type',
            field=models.CharField(choices=[('考试', '考试'), ('模拟', '模拟'), ('作业', '作业')], max_length=10, verbose_name='考试类型'),
        ),
        migrations.AlterField(
            model_name='exammanage',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='考试管理封存（考试完了，永不可动）'),
        ),
        migrations.AlterField(
            model_name='exammanage',
            name='last_modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='考试管理最后一次修改时间'),
        ),
        migrations.AlterField(
            model_name='exammanage',
            name='max_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='满分值设置'),
        ),
    ]
