# encoding=utf-8
# Generated by Django 3.2.23 on 2024-03-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_manage', '0002_auto_20240228_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammanage',
            name='multiple_half',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='多选题 默认false，少选不得分； true则少选得一半的分'),
        ),
        migrations.AlterField(
            model_name='exammanage',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='考试时长'),
        ),
    ]
