# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-31 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_auto_20240131_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'permissions': [('can_get', '用户或组可获取该菜单')], 'verbose_name': '功能板块'},
        ),
    ]
