# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='菜单排列次序'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
