# encoding=utf-8
# Generated by Django 3.2.23 on 2024-02-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_alter_submodule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='submodule',
            name='role_can_get',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='角色可见'),
        ),
    ]
