# Generated by Django 3.2.23 on 2024-03-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_submodule_role_can_get'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色',
                'db_table': 'modules_roles',
            },
        ),
    ]
