# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('stu_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='学号')),
                ('tel', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='手机号')),
                ('id_card', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('modules', models.TextField(blank=True, null=True, verbose_name='板块权限')),
                ('is_staff', models.BooleanField(default=False, help_text='是否是教师', verbose_name='教职工')),
                ('is_active', models.BooleanField(default=True, help_text='账户是否有效', verbose_name='激活状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
    ]
