# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='头像'),
        ),
    ]
