# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-31 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份'),
        ),
    ]
