# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='modules',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='是否平台工作人员', verbose_name=''),
        ),
    ]
