# Generated by Django 3.2.23 on 2024-03-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='学科'),
        ),
    ]
