# Generated by Django 3.2.23 on 2024-03-10 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='subject',
        ),
    ]
