# Generated by Django 3.2.23 on 2024-03-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject_manage', '0002_subjectstaffgroup_user'),
        ('video', '0004_remove_video_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subject_manage.subject', verbose_name='学科'),
        ),
    ]
