# encoding=utf-8
# Generated by Django 3.2.23 on 2024-02-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='描述')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='公告创建时间')),
                ('last_modified_time', models.DateTimeField(auto_now=True, verbose_name='公告最新更新时间')),
            ],
            options={
                'verbose_name': '公告管理',
                'db_table': 'notice',
            },
        ),
    ]
