# encoding=utf-8
# Generated by Django 3.2.23 on 2024-03-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_rename_exam_manage_pk_noticemanageclass_notice_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticemanage',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='归档，不可见'),
        ),
        migrations.AddField(
            model_name='noticemanage',
            name='valid_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='公告有效期'),
        ),
    ]
