# encoding=utf-8
# Generated by Django 3.2.23 on 2024-01-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exam_manage', '0001_initial'),
        ('question_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScoreResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('stu_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='学号')),
                ('objective_score', models.IntegerField(blank=True, null=True, verbose_name='客观题得分')),
                ('subjective_score', models.IntegerField(blank=True, null=True, verbose_name='主观题得分')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='总分')),
                ('sub_block', models.BooleanField(blank=True, default=False, null=True, verbose_name='终止提交客观题')),
            ],
            options={
                'verbose_name': '学生考试答卷成绩',
                'db_table': 'exam_score_result',
            },
        ),
        migrations.CreateModel(
            name='ExamSubjectiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_answer', models.TextField(blank=True, null=True, verbose_name='学生答卷')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='分数')),
                ('sub_block', models.BooleanField(blank=True, default=False, null=True, verbose_name='评分完毕')),
                ('exam_manage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam_manage.exammanage', verbose_name='考试场次')),
                ('exam_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question_manage.examquestion', verbose_name='主观题试题')),
            ],
            options={
                'verbose_name': '学生考试主观题答卷',
                'db_table': 'exam_subjective_result',
            },
        ),
    ]
