# encoding=utf-8
# Generated by Django 3.2.23 on 2024-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_score', '0003_auto_20240303_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsubjectiveresult',
            name='sub_obj',
            field=models.CharField(blank=True, choices=[('主观', '主观'), ('客观', '客观')], max_length=20, null=True, verbose_name='主客观'),
        ),
    ]
