# Generated by Django 3.2.23 on 2024-03-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='发送人（非User）')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='标题')),
                ('text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='正文')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '消息管理',
                'db_table': 'message',
            },
        ),
    ]
